[toolchain]
anchor_version = "0.30.1"

[features]
seeds = true
skip-lint = false

[programs.devnet]
geass_predictions = "BwjuHiMenCuF45T82rMerzeqgbVQLqrKyxmb5pyBD4xm"

[programs.mainnet]
geass_predictions = "BwjuHiMenCuF45T82rMerzeqgbVQLqrKyxmb5pyBD4xm"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/geass-predictions"]
